### ISSUE TITLE
Symbol ws2812b multiply defined (by ws2812b.o and viseffect.o)

### ISSUE THREAD

**Issue by mnemocron** [hubmartin/WS2812B_STM32F103#1]
I am porting your example to a Keil uVision Project with a different HAL dialect and I encountered the following error.

```
STM32f1_NeoPixel_Test\STM32f1_NeoPixel_Test.axf: 
Error: L6200E: Symbol ws2812b multiply defined (by ws2812b.o and viseffect.o).
```

I stumbled upon this reply on [Stackoverflow](https://stackoverflow.com/questions/14870423/symbol-is-multiply-defined)

so in the file `src/ws2812b.h` I deleted `line 76` `WS2812_Struct ws2812b;` and copied it to the file `src/visEffect.c` after `line 29` and the compiler was satisfied.

**Comment by yurenchen000** [comment]
ubuntu 22, amd64
arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi

meet the same situation, fixed use your way

**Comment by elmout31** [comment]
Thanks "hub martin" for your work.

I port on STMCubeIDE (1.18.1) same issue. Here is the fix. 
1) inside ws2812b.h change  `WS2812_Struct ws2812b;` by
`extern WS2812_Struct disp;`
2) inside ws2812.c add just after the #include
`WS2812_Struct disp;`
3) inisde visEffect.c add just after the #include
`extern WS2812_Struct disp;`
4) Inside ws2812b.c and visEffect.c replace all "ws2812b." by "disp." EXCEPT for  `#include "ws2812b.h" `lines
Enjoy
